### ISSUE TITLE
index.rmd is missing during knitting

### ISSUE THREAD

**Issue by RinsRutgers** [uashogeschoolutrecht/redamoi#11]
@Maddocent Heb jij enig idee wat hier mis is?

**Comment by RinsRutgers** [comment]
`
output file: ch02-intro.knit.md

Error in file(con, "r") : cannot open the connection
Calls: <Anonymous> ... mapply -> <Anonymous> -> read_utf8 -> readLines -> file
In addition: Warning message:
In file(con, "r") : cannot open file 'index.md': No such file or directory
Execution halted
There were 18 warnings (use warnings() to see them)`

**Comment by Maddocent** [comment]
Ik ga het proberen uit te zoeken.

Grt
Marc

Outlook voor Android downloaden<https://aka.ms/ghei36>

________________________________
From: RinsRutgers ***@***.***>
Sent: Wednesday, February 16, 2022 7:21:20 AM
To: uashogeschoolutrecht/redamoi ***@***.***>
Cc: Marc Teunis ***@***.***>; Assign ***@***.***>
Subject: [uashogeschoolutrecht/redamoi] index.rmd is missing during knitting (Issue #11)


@Maddocent<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMaddocent&data=04%7C01%7Cmarc.teunis%40hu.nl%7C132fcfc88ce74e202fc308d9f1148d21%7C989329099a5a4d18ace47236b5b5e11d%7C0%7C0%7C637805892863794152%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=KDuSKZ4OcpzZ7Zel3GmYM7ymmGRtCiOowQHJ15nZsh4%3D&reserved=0> Heb jij enig idee wat hier mis is?

**Comment by Maddocent** [comment]
Dit is een bookdown project. Het knitten van losse Rmd's werkt niet in dit project. Om een losse Rmd te knitten moet je de file verplaatsen naar een nieuw RStudio project. Let er op dat sommige Rmd's dependencies hebben zoals figuren. Deze moet je dan mee kopiëren.

**Comment by Maddocent** [comment]
Ook, na een google actie: https://github.com/ismayc/thesisdown/issues/12 This might be related to the issue reported here.
